"""Deterministic Obsidian homepage (``wiki/index.md``) skeleton + managed cards.

gen-home builds a *skeleton*: an Obsidian-native page frame (overview line, the
Bases embed ``![[index.base#主题总览]]``, a topic-navigation table scaffold and a
relationship-graph placeholder) plus one managed, regenerable region — the
"工作区" — delimited by HTML markers. The agent fills the semantic prose (topic
grouping, 范围 cells, relationship narrative); only the managed region is
script-owned and refreshed on every run, so re-running never clobbers agent
edits outside the markers.

The managed region renders captured reports / graphs as a responsive,
centered card grid via a Dataview ``dataviewjs`` query when Dataview + its JS
queries are available, else as a static NFC-sorted Markdown list. No wall-clock
timestamps, so output is byte-identical for a fixed vault. This module never
touches ``index.base`` or any ``.base`` file.
"""

from __future__ import annotations

import unicodedata
from pathlib import Path

from . import config, frontmatter

EMBED = "![[index.base#主题总览]]"
AUTO_START = "<!-- agent-wiki:auto start — generated by gen-home; do not edit inside -->"
AUTO_END = "<!-- agent-wiki:auto end -->"
PLACEHOLDER = "_待补充_"

# dataviewjs card block: scans wiki/queries|graphs relative to this note
# and renders clickable, theme-aware cards in a centered flex grid. Centering
# makes the trailing (short) row balanced instead of left-aligned with a gap;
# cards grow within [168px, 232px] so any item count fills rows evenly.
_CARDS_JS = """```dataviewjs
const root = dv.current().file.folder;
const groups = [
  { title: "🔎 检索报告", dir: root + "/queries", ext: "md" },
  { title: "🕸 图谱", dir: root + "/graphs", ext: "canvas" },
];
const style = dv.container.createEl("style");
style.textContent = `
.aw-grid{display:flex;flex-wrap:wrap;justify-content:center;gap:.75rem;margin:.5rem 0 1.25rem}
.aw-card{flex:1 1 168px;max-width:232px;min-height:44px;display:flex;align-items:center;justify-content:center;text-align:center;padding:.7rem .9rem;border:1px solid var(--background-modifier-border);border-radius:12px;background:var(--background-secondary);color:var(--text-normal);text-decoration:none;font-weight:500;box-shadow:0 1px 2px rgba(0,0,0,.06);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}
.aw-card:hover{transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,.12);border-color:var(--interactive-accent)}
.aw-card:focus-visible{outline:2px solid var(--interactive-accent);outline-offset:2px}
.aw-card:active{transform:translateY(0)}
@media (prefers-reduced-motion:reduce){.aw-card{transition:none}}
`;
for (const g of groups) {
  dv.header(3, g.title);
  const files = app.vault.getFiles()
    .filter(f => f.extension === g.ext && f.path.startsWith(g.dir + "/"))
    .sort((a, b) => a.basename.localeCompare(b.basename));
  if (!files.length) { dv.paragraph("_（空）_"); continue; }
  const grid = dv.container.createEl("div", { cls: "aw-grid" });
  for (const f of files) {
    const card = grid.createEl("a", { cls: "internal-link aw-card", href: f.path });
    card.dataset.href = f.path;
    card.setText(f.basename);
  }
}
```"""


def _nfc(value: str) -> str:
    return unicodedata.normalize("NFC", value)


def _tiles(directory: Path, ext: str) -> list[tuple[str, str]]:
    """``(label, wiki-relative POSIX path)`` per ``*{ext}`` file, NFC-sorted;
    empty when the directory is missing."""
    if not directory.exists():
        return []
    files = sorted(directory.glob(f"*{ext}"), key=lambda p: _nfc(p.name))
    return [(_nfc(p.stem), f"{directory.name}/{_nfc(p.name)}") for p in files]


def _callout(kind: str, title: str, tiles: list[tuple[str, str]]) -> str:
    lines = [f"> [!{kind}] {title}"]
    if tiles:
        lines += [f"> - [{label}]({path})" for label, path in tiles]
    else:
        lines.append("> _（空）_")
    return "\n".join(lines)


def _topic_rows(vault: str | Path) -> list[tuple[str, int]]:
    """``(topic-name, source-count)`` per ``wiki/topics/*.md``, NFC-sorted. Count
    is the frontmatter ``sources`` length (0 when absent/unparsable)."""
    topics_dir = config.topics_dir(vault)
    if not topics_dir.exists():
        return []
    rows: list[tuple[str, int]] = []
    for path in sorted(topics_dir.glob("*.md"), key=lambda p: _nfc(p.name)):
        count = 0
        try:
            meta, _ = frontmatter.parse(path.read_text(encoding="utf-8-sig"))
            sources = meta.get("sources")
            count = len(sources) if isinstance(sources, list) else 0
        except (OSError, UnicodeDecodeError, frontmatter.FrontmatterError):
            count = 0
        rows.append((_nfc(path.stem), count))
    return rows


def _nav_table(rows: list[tuple[str, int]]) -> str:
    if not rows:
        return f"{PLACEHOLDER}（暂无主题页；运行 index 后由 agent 分组并补全范围）"
    lines = ["| 主题 | 篇数 | 范围 |", "|---|---|---|"]
    lines += [f"| [[{name}]] | {count} | {PLACEHOLDER} |" for name, count in rows]
    return "\n".join(lines)


def _workspace_body(vault: str | Path, cards: bool) -> str:
    """The 工作区 section body (heading + content); cards or static fallback."""
    if cards:
        callout = (
            "> [!abstract] 由 agent-wiki 自动维护（Dataview 动态卡片）\n"
            "> 检索报告 / 图谱 由 Dataview 实时扫描 `queries`、`graphs` 文件夹，"
            "新增文件自动出现，无需手改。"
        )
        return f"## 🗂 工作区\n\n{callout}\n\n{_CARDS_JS}"
    note = (
        "> [!tip] 工作区（静态列表）\n"
        "> 未检测到 Dataview 插件或其 JavaScript 查询未开启，已改用静态链接。"
        "安装 Dataview 并在其设置中开启「Enable JavaScript Queries」后重跑 `gen-home` 即可获得动态卡片。"
    )
    queries = _callout("info", "🔎 检索报告", _tiles(config.queries_dir(vault), ".md"))
    graphs = _callout("note", "🕸 图谱", _tiles(config.graphs_dir(vault), ".canvas"))
    return f"## 🗂 工作区\n\n{note}\n\n{queries}\n\n{graphs}"


def managed_block(vault: str | Path, cards: bool) -> str:
    """The marker-delimited, script-owned 工作区 region (idempotent)."""
    return f"{AUTO_START}\n\n{_workspace_body(vault, cards)}\n\n{AUTO_END}"


def render_skeleton(vault: str | Path, cards: bool) -> str:
    """The full first-run page: frame + Bases embed + nav-table scaffold +
    relationship placeholder + managed workspace region."""
    rows = _topic_rows(vault)
    total = sum(count for _, count in rows)
    blocks = [
        "# Wiki Index",
        f"> 文献阅读记录知识库 · {len(rows)} 个主题 · 来源合计 {total}（含跨主题重复）。{PLACEHOLDER}：概述可由 agent 补充。",
        "## 🧭 动态视图（Bases）",
        "> 可排序 / 可筛选的实时主题表（依赖 Bases 核心插件）。",
        EMBED,
        "## 📚 主题导航",
        _nav_table(rows),
        "## 🔗 主题关系图谱",
        f"{PLACEHOLDER}：由 agent 依据主题间的机理 / 材料 / 应用关系生成叙述。",
        managed_block(vault, cards),
    ]
    return "\n\n".join(blocks) + "\n"


def _is_placeholder(text: str) -> bool:
    return text.strip() in ("", "# Wiki Index")


def merge(existing: str | None, vault: str | Path, cards: bool) -> str:
    """Produce index.md content. Empty/placeholder -> full skeleton. Existing
    managed markers -> refresh only that region (preserve agent prose). Existing
    content without markers -> append the managed region (never clobber)."""
    block = managed_block(vault, cards)
    if existing is None or _is_placeholder(existing):
        return render_skeleton(vault, cards)
    start = existing.find(AUTO_START)
    if start != -1:
        end = existing.find(AUTO_END, start + len(AUTO_START))
        if end != -1:
            return existing[:start] + block + existing[end + len(AUTO_END):]
    return existing.rstrip("\n") + "\n\n" + block + "\n"
